### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by limatheus** [diasfulvio/zipcode#1]
Olá @diasfulvio,

Fui utlizar o ZipCode em uma API, adicionei o Service Provider e o Alias, mas quando vou consultar um CEP me retorna a mensagem abaixo:

```Class 'Canducci\ZipCode\Providers\ZipCodeServiceProvider' not found```

Criei uma instalação limpa e aconteceu a mesma coisa, o que pode ser?

Obrigado

**Comment by diasfulvio** [comment]
Tinha um erro de namespace, foi solucionado
